/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.dealers;

/**
 *
 * @author El Rey
 */
public class createDealerView extends javax.swing.JFrame {

    /**
     * Creates new form createDealer
     */
    public createDealerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        addDealerButton = new javax.swing.JButton();
        lastNameDealerField = new javax.swing.JTextField();
        dealerNamerField = new javax.swing.JTextField();
        idDealerField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dealerProductField = new javax.swing.JTextField();
        celDealerField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        backButtonDealer = new javax.swing.JButton();
        principalMenuButtonDealer = new javax.swing.JButton();
        priceProductDealer = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        brandProductDealer = new javax.swing.JTextField();
        Brand = new javax.swing.JLabel();
        Brand1 = new javax.swing.JLabel();
        brandProductDealer1 = new javax.swing.JTextField();
        Quantify1 = new javax.swing.JLabel();
        quantifyProductDealer1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(196, 196, 196));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Ingrese los datos del distribuidor");
        jTextField1.setBorder(null);
        jTextField1.setMaximumSize(new java.awt.Dimension(0, 0));
        jTextField1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 10, 560, 100);

        jTextField17.setBackground(new java.awt.Color(196, 196, 196));
        jTextField17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("Developed by jviedman dev - enriquez dev");
        jTextField17.setBorder(null);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(260, 610, 520, 19);

        addDealerButton.setBackground(new java.awt.Color(131, 131, 131));
        addDealerButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addDealerButton.setText("Guardar distribuidor");
        addDealerButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        addDealerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDealerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addDealerButton);
        addDealerButton.setBounds(400, 510, 230, 60);

        lastNameDealerField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lastNameDealerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameDealerFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameDealerField);
        lastNameDealerField.setBounds(290, 320, 180, 40);

        dealerNamerField.setForeground(new java.awt.Color(204, 204, 204));
        dealerNamerField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dealerNamerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerNamerFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dealerNamerField);
        dealerNamerField.setBounds(290, 170, 180, 40);

        idDealerField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        idDealerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDealerFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idDealerField);
        idDealerField.setBounds(290, 250, 180, 40);

        jLabel4.setBackground(new java.awt.Color(196, 196, 196));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("<html>ID</html>");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 240, 90, 60);

        jLabel7.setBackground(new java.awt.Color(196, 196, 196));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("<html>Apellido</html>");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel7.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel7.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel7.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 300, 100, 70);

        jLabel8.setBackground(new java.awt.Color(196, 196, 196));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("<html>Nombre</html>");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel8.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel8.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel8.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 150, 110, 70);

        jLabel5.setBackground(new java.awt.Color(196, 196, 196));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("<html>Producto</html>");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel5.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(560, 120, 110, 60);

        dealerProductField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dealerProductField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerProductFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dealerProductField);
        dealerProductField.setBounds(700, 130, 180, 40);

        celDealerField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        celDealerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celDealerFieldActionPerformed(evt);
            }
        });
        jPanel1.add(celDealerField);
        celDealerField.setBounds(290, 390, 180, 40);

        jLabel6.setBackground(new java.awt.Color(196, 196, 196));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("<html>Celular</html>");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel6.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 380, 90, 60);

        backButtonDealer.setBackground(new java.awt.Color(131, 131, 131));
        backButtonDealer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        backButtonDealer.setText("Volver");
        backButtonDealer.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        backButtonDealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonDealerActionPerformed(evt);
            }
        });
        jPanel1.add(backButtonDealer);
        backButtonDealer.setBounds(260, 510, 130, 60);

        principalMenuButtonDealer.setBackground(new java.awt.Color(131, 131, 131));
        principalMenuButtonDealer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        principalMenuButtonDealer.setText("Menu principal");
        principalMenuButtonDealer.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        principalMenuButtonDealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalMenuButtonDealerActionPerformed(evt);
            }
        });
        jPanel1.add(principalMenuButtonDealer);
        principalMenuButtonDealer.setBounds(640, 510, 230, 60);

        priceProductDealer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        priceProductDealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceProductDealerActionPerformed(evt);
            }
        });
        jPanel1.add(priceProductDealer);
        priceProductDealer.setBounds(700, 330, 180, 40);

        price.setBackground(new java.awt.Color(196, 196, 196));
        price.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        price.setForeground(new java.awt.Color(0, 0, 0));
        price.setText("<html>Precio</html>");
        price.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        price.setMaximumSize(new java.awt.Dimension(0, 0));
        price.setMinimumSize(new java.awt.Dimension(0, 0));
        price.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(price);
        price.setBounds(560, 320, 110, 60);

        brandProductDealer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        brandProductDealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandProductDealerActionPerformed(evt);
            }
        });
        jPanel1.add(brandProductDealer);
        brandProductDealer.setBounds(700, 190, 180, 40);

        Brand.setBackground(new java.awt.Color(196, 196, 196));
        Brand.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Brand.setForeground(new java.awt.Color(0, 0, 0));
        Brand.setText("<html>Marca</html>");
        Brand.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Brand.setMaximumSize(new java.awt.Dimension(0, 0));
        Brand.setMinimumSize(new java.awt.Dimension(0, 0));
        Brand.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(Brand);
        Brand.setBounds(560, 180, 110, 60);

        Brand1.setBackground(new java.awt.Color(196, 196, 196));
        Brand1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Brand1.setForeground(new java.awt.Color(0, 0, 0));
        Brand1.setText("<html>ID del producto</html>");
        Brand1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Brand1.setMaximumSize(new java.awt.Dimension(0, 0));
        Brand1.setMinimumSize(new java.awt.Dimension(0, 0));
        Brand1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(Brand1);
        Brand1.setBounds(560, 250, 110, 60);

        brandProductDealer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        brandProductDealer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandProductDealer1ActionPerformed(evt);
            }
        });
        jPanel1.add(brandProductDealer1);
        brandProductDealer1.setBounds(700, 260, 180, 40);

        Quantify1.setBackground(new java.awt.Color(196, 196, 196));
        Quantify1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Quantify1.setForeground(new java.awt.Color(0, 0, 0));
        Quantify1.setText("<html>Cantidad</html>");
        Quantify1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Quantify1.setMaximumSize(new java.awt.Dimension(0, 0));
        Quantify1.setMinimumSize(new java.awt.Dimension(0, 0));
        Quantify1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(Quantify1);
        Quantify1.setBounds(560, 390, 110, 60);

        quantifyProductDealer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        quantifyProductDealer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantifyProductDealer1ActionPerformed(evt);
            }
        });
        jPanel1.add(quantifyProductDealer1);
        quantifyProductDealer1.setBounds(700, 390, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDealerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDealerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDealerButtonActionPerformed

    private void lastNameDealerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameDealerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameDealerFieldActionPerformed

    private void dealerNamerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerNamerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealerNamerFieldActionPerformed

    private void idDealerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDealerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDealerFieldActionPerformed

    private void dealerProductFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerProductFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealerProductFieldActionPerformed

    private void celDealerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celDealerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celDealerFieldActionPerformed

    private void backButtonDealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonDealerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonDealerActionPerformed

    private void principalMenuButtonDealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalMenuButtonDealerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principalMenuButtonDealerActionPerformed

    private void priceProductDealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceProductDealerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceProductDealerActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void brandProductDealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandProductDealerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandProductDealerActionPerformed

    private void brandProductDealer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandProductDealer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandProductDealer1ActionPerformed

    private void quantifyProductDealer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantifyProductDealer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantifyProductDealer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createDealerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createDealerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createDealerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createDealerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createDealerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Brand;
    private javax.swing.JLabel Brand1;
    private javax.swing.JLabel Quantify1;
    public javax.swing.JButton addDealerButton;
    public javax.swing.JButton backButtonDealer;
    public javax.swing.JTextField brandProductDealer;
    public javax.swing.JTextField brandProductDealer1;
    public javax.swing.JTextField celDealerField;
    public javax.swing.JTextField dealerNamerField;
    public javax.swing.JTextField dealerProductField;
    public javax.swing.JTextField idDealerField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField17;
    public javax.swing.JTextField lastNameDealerField;
    private javax.swing.JLabel price;
    public javax.swing.JTextField priceProductDealer;
    public javax.swing.JButton principalMenuButtonDealer;
    public javax.swing.JTextField quantifyProductDealer1;
    // End of variables declaration//GEN-END:variables
}
