/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.dealers;

/**
 *
 * @author Daniel Enriquez
 */
public class showDealersView extends javax.swing.JFrame {

    /**
     * Creates new form showDealers
     */
    public showDealersView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        dealersBackButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        nameDealer = new javax.swing.JLabel();
        idDealer = new javax.swing.JLabel();
        celDealer = new javax.swing.JLabel();
        lastNameDealer = new javax.swing.JLabel();
        principalMenuDealersButton = new javax.swing.JButton();
        productDealer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setLayout(null);

        jTextField17.setBackground(new java.awt.Color(196, 196, 196));
        jTextField17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("Developed by jviedman dev - enriquez dev");
        jTextField17.setBorder(null);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(260, 600, 520, 19);

        dealersBackButton.setBackground(new java.awt.Color(131, 131, 131));
        dealersBackButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        dealersBackButton.setText("Volver");
        dealersBackButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        dealersBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealersBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dealersBackButton);
        dealersBackButton.setBounds(280, 510, 210, 60);

        jTextField2.setBackground(new java.awt.Color(196, 196, 196));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Datos del distribuidor");
        jTextField2.setBorder(null);
        jTextField2.setMaximumSize(new java.awt.Dimension(0, 0));
        jTextField2.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextField2.setPreferredSize(new java.awt.Dimension(0, 0));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(310, 30, 370, 100);

        nameDealer.setForeground(new java.awt.Color(0, 0, 0));
        nameDealer.setText("jLabel1");
        nameDealer.setMinimumSize(new java.awt.Dimension(80, 80));
        nameDealer.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(nameDealer);
        nameDealer.setBounds(470, 180, 100, 30);
        nameDealer.setSize(100,100);

        idDealer.setForeground(new java.awt.Color(0, 0, 0));
        idDealer.setText("jLabel1");
        jPanel1.add(idDealer);
        idDealer.setBounds(470, 280, 120, 40);

        celDealer.setForeground(new java.awt.Color(0, 0, 0));
        celDealer.setText("jLabel1");
        jPanel1.add(celDealer);
        celDealer.setBounds(470, 380, 120, 40);

        lastNameDealer.setForeground(new java.awt.Color(0, 0, 0));
        lastNameDealer.setText("jLabel1");
        jPanel1.add(lastNameDealer);
        lastNameDealer.setBounds(470, 230, 120, 40);

        principalMenuDealersButton.setBackground(new java.awt.Color(131, 131, 131));
        principalMenuDealersButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        principalMenuDealersButton.setText("Menu Principal");
        principalMenuDealersButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        principalMenuDealersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalMenuDealersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(principalMenuDealersButton);
        principalMenuDealersButton.setBounds(510, 510, 210, 60);

        productDealer.setForeground(new java.awt.Color(0, 0, 0));
        productDealer.setText("jLabel1");
        jPanel1.add(productDealer);
        productDealer.setBounds(470, 330, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dealersBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealersBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealersBackButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void principalMenuDealersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalMenuDealersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principalMenuDealersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showDealersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showDealersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showDealersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showDealersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showDealersView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel celDealer;
    public javax.swing.JButton dealersBackButton;
    public javax.swing.JLabel idDealer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JLabel lastNameDealer;
    public javax.swing.JLabel nameDealer;
    public javax.swing.JButton principalMenuDealersButton;
    public javax.swing.JLabel productDealer;
    // End of variables declaration//GEN-END:variables
}
