/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author El Rey
 */
public class searchItemView extends javax.swing.JFrame {

    /**
     * Creates new form searchOptionView
     */
    public searchItemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        selectClientButton = new javax.swing.JButton();
        selectDealerItem = new javax.swing.JButton();
        searchProductButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(195, 195, 195));
        jPanel3.setMaximumSize(new java.awt.Dimension(950, 600));
        jPanel3.setMinimumSize(new java.awt.Dimension(950, 600));
        jPanel3.setLayout(null);

        jTextField3.setBackground(new java.awt.Color(196, 196, 196));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Developed by jviedman dev - enriquez dev");
        jTextField3.setBorder(null);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(220, 570, 520, 19);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("¿Qué ítem desea buscar?");
        jLabel6.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel6.setPreferredSize(new java.awt.Dimension(435, 90));
        jPanel3.add(jLabel6);
        jLabel6.setBounds(170, 120, 610, 50);

        selectClientButton.setBackground(new java.awt.Color(131, 131, 131));
        selectClientButton.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        selectClientButton.setText("Cliente");
        selectClientButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.black));
        selectClientButton.setMaximumSize(new java.awt.Dimension(170, 75));
        selectClientButton.setMinimumSize(new java.awt.Dimension(170, 75));
        selectClientButton.setPreferredSize(new java.awt.Dimension(170, 75));
        selectClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectClientButtonActionPerformed(evt);
            }
        });
        jPanel3.add(selectClientButton);
        selectClientButton.setBounds(140, 330, 170, 50);

        selectDealerItem.setBackground(new java.awt.Color(131, 131, 131));
        selectDealerItem.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        selectDealerItem.setText("Distribuidor");
        selectDealerItem.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.black));
        selectDealerItem.setMaximumSize(new java.awt.Dimension(170, 75));
        selectDealerItem.setMinimumSize(new java.awt.Dimension(170, 75));
        selectDealerItem.setPreferredSize(new java.awt.Dimension(170, 75));
        selectDealerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDealerItemActionPerformed(evt);
            }
        });
        jPanel3.add(selectDealerItem);
        selectDealerItem.setBounds(360, 330, 250, 50);

        searchProductButton.setBackground(new java.awt.Color(131, 131, 131));
        searchProductButton.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        searchProductButton.setText("Producto");
        searchProductButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.black));
        searchProductButton.setMaximumSize(new java.awt.Dimension(170, 75));
        searchProductButton.setMinimumSize(new java.awt.Dimension(170, 75));
        searchProductButton.setPreferredSize(new java.awt.Dimension(170, 75));
        searchProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductButtonActionPerformed(evt);
            }
        });
        jPanel3.add(searchProductButton);
        searchProductButton.setBounds(650, 330, 180, 50);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Universidad del Valle");
        jLabel7.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel7.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel7.setPreferredSize(new java.awt.Dimension(435, 90));
        jPanel3.add(jLabel7);
        jLabel7.setBounds(270, 40, 435, 90);

        backButton.setBackground(new java.awt.Color(195, 195, 195));
        backButton.setBorder(null);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel3.add(backButton);
        backButton.setBounds(70, 60, 80, 87);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectClientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectClientButtonActionPerformed

    private void selectDealerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDealerItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectDealerItemActionPerformed

    private void searchProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProductButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchItemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    public javax.swing.JButton searchProductButton;
    public javax.swing.JButton selectClientButton;
    public javax.swing.JButton selectDealerItem;
    // End of variables declaration//GEN-END:variables
}
