/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.products;

/**
 *
 * @author El Rey
 */
public class showProductsView extends javax.swing.JFrame {

    /**
     * Creates new form showProductsView
     */
    public showProductsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        principalMenuButton = new javax.swing.JButton();
        productPrice = new javax.swing.JLabel();
        productBrand = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        productId = new javax.swing.JLabel();
        productQuantity = new javax.swing.JLabel();
        backButtonProducts = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(196, 196, 196));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Datos del producto ");
        jTextField1.setBorder(null);
        jTextField1.setMaximumSize(new java.awt.Dimension(0, 0));
        jTextField1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 20, 350, 100);

        jTextField17.setBackground(new java.awt.Color(196, 196, 196));
        jTextField17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("Developed by jviedman dev - enriquez dev");
        jTextField17.setBorder(null);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(230, 560, 520, 19);

        principalMenuButton.setBackground(new java.awt.Color(131, 131, 131));
        principalMenuButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        principalMenuButton.setText("Menu principal");
        principalMenuButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        principalMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalMenuButtonActionPerformed(evt);
            }
        });
        jPanel1.add(principalMenuButton);
        principalMenuButton.setBounds(470, 470, 180, 60);

        productPrice.setBackground(new java.awt.Color(196, 196, 196));
        productPrice.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        productPrice.setForeground(new java.awt.Color(0, 0, 0));
        productPrice.setText("<html>Precio</html>");
        productPrice.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        productPrice.setMaximumSize(new java.awt.Dimension(0, 0));
        productPrice.setMinimumSize(new java.awt.Dimension(0, 0));
        productPrice.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(productPrice);
        productPrice.setBounds(330, 260, 440, 60);

        productBrand.setBackground(new java.awt.Color(196, 196, 196));
        productBrand.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        productBrand.setForeground(new java.awt.Color(0, 0, 0));
        productBrand.setText("<html>Marca</html>");
        productBrand.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        productBrand.setMaximumSize(new java.awt.Dimension(0, 0));
        productBrand.setMinimumSize(new java.awt.Dimension(0, 0));
        productBrand.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(productBrand);
        productBrand.setBounds(330, 190, 440, 70);

        productName.setBackground(new java.awt.Color(196, 196, 196));
        productName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        productName.setForeground(new java.awt.Color(0, 0, 0));
        productName.setText("<html>Nombre</html>");
        productName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        productName.setMaximumSize(new java.awt.Dimension(0, 0));
        productName.setMinimumSize(new java.awt.Dimension(0, 0));
        productName.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(productName);
        productName.setBounds(330, 140, 500, 60);

        productId.setBackground(new java.awt.Color(196, 196, 196));
        productId.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        productId.setForeground(new java.awt.Color(0, 0, 0));
        productId.setText("<html>ID</html>");
        productId.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        productId.setMaximumSize(new java.awt.Dimension(0, 0));
        productId.setMinimumSize(new java.awt.Dimension(0, 0));
        productId.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(productId);
        productId.setBounds(330, 380, 330, 40);

        productQuantity.setBackground(new java.awt.Color(196, 196, 196));
        productQuantity.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        productQuantity.setForeground(new java.awt.Color(0, 0, 0));
        productQuantity.setText("<html>Cantidad</html>");
        productQuantity.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        productQuantity.setMaximumSize(new java.awt.Dimension(0, 0));
        productQuantity.setMinimumSize(new java.awt.Dimension(0, 0));
        productQuantity.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(productQuantity);
        productQuantity.setBounds(330, 310, 410, 70);

        backButtonProducts.setBackground(new java.awt.Color(131, 131, 131));
        backButtonProducts.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        backButtonProducts.setText("Volver");
        backButtonProducts.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        backButtonProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonProductsActionPerformed(evt);
            }
        });
        jPanel1.add(backButtonProducts);
        backButtonProducts.setBounds(310, 470, 130, 60);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Mega\\Univalle\\III semestre\\POE\\Projects\\MiniProyecto-4\\src\\main\\java\\resources\\LogoUnivalle.jpeg")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(740, 30, 200, 260);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Mega\\Univalle\\III semestre\\POE\\Projects\\MiniProyecto-4\\src\\main\\java\\resources\\LogoUnivalle.jpeg")); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 30, 200, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void principalMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principalMenuButtonActionPerformed

    private void backButtonProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showProductsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButtonProducts;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField17;
    public javax.swing.JButton principalMenuButton;
    public javax.swing.JLabel productBrand;
    public javax.swing.JLabel productId;
    public javax.swing.JLabel productName;
    public javax.swing.JLabel productPrice;
    public javax.swing.JLabel productQuantity;
    // End of variables declaration//GEN-END:variables
}
