/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.buy;

/**
 *
 * @author Juan
 */
public class buyView extends javax.swing.JFrame {

    /**
     * Creates new form buyView
     */
    public buyView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productAvaliableLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buyProduct = new javax.swing.JButton();
        backButtonBuy = new javax.swing.JButton();
        principalMenuButtonVerify = new javax.swing.JButton();
        idDealer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(195, 195, 195));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 600));
        jPanel1.setLayout(null);

        productAvaliableLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        productAvaliableLabel.setForeground(new java.awt.Color(0, 0, 0));
        productAvaliableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productAvaliableLabel.setText("Producto disponible:");
        jPanel1.add(productAvaliableLabel);
        productAvaliableLabel.setBounds(200, 280, 220, 80);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Comprar productos");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 70, 570, 50);

        buyProduct.setBackground(new java.awt.Color(131, 131, 131));
        buyProduct.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buyProduct.setText("Menu principal");
        buyProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        buyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyProductActionPerformed(evt);
            }
        });
        jPanel1.add(buyProduct);
        buyProduct.setBounds(640, 450, 210, 60);

        backButtonBuy.setBackground(new java.awt.Color(131, 131, 131));
        backButtonBuy.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        backButtonBuy.setText("Volver");
        backButtonBuy.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        backButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonBuyActionPerformed(evt);
            }
        });
        jPanel1.add(backButtonBuy);
        backButtonBuy.setBounds(250, 450, 120, 60);

        principalMenuButtonVerify.setBackground(new java.awt.Color(131, 131, 131));
        principalMenuButtonVerify.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        principalMenuButtonVerify.setText("Verificar");
        principalMenuButtonVerify.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        principalMenuButtonVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalMenuButtonVerifyActionPerformed(evt);
            }
        });
        jPanel1.add(principalMenuButtonVerify);
        principalMenuButtonVerify.setBounds(400, 450, 210, 60);

        idDealer.setForeground(new java.awt.Color(0, 0, 0));
        idDealer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idDealer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        idDealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDealerActionPerformed(evt);
            }
        });
        jPanel1.add(idDealer);
        idDealer.setBounds(510, 180, 80, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingrese el ID del proveedor");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 160, 220, 80);

        quantityLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(0, 0, 0));
        quantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(quantityLabel);
        quantityLabel.setBounds(610, 240, 270, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 950, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonBuyActionPerformed

    private void principalMenuButtonVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalMenuButtonVerifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principalMenuButtonVerifyActionPerformed

    private void idDealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDealerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDealerActionPerformed

    private void buyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButtonBuy;
    public javax.swing.JButton buyProduct;
    public javax.swing.JTextField idDealer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton principalMenuButtonVerify;
    public javax.swing.JLabel productAvaliableLabel;
    public javax.swing.JLabel quantityLabel;
    // End of variables declaration//GEN-END:variables
}
